FROM openjdk:8-jdk

WORKDIR /usr/src/minecraft

RUN curl -fSL -o /tmp/server.jar https://piston-data.mojang.com/v1/objects/1b557e7b033b583cd9f66746b7a9ab1ec1673ced/server.jar

RUN echo "eula=true" > /tmp/eula.txt

EXPOSE 25565

CMD ["/bin/bash", "-c", "cp -n /tmp/server.jar /usr/src/minecraft/ && cp -n /tmp/eula.txt /usr/src/minecraft/ && java -Xmx6144M -Xms6144M -jar /usr/src/minecraft/server.jar nogui"]
